name: Sync Production to Staging

# Trigger on any push to phoenixcloud-production
on:
  push:
    branches:
      - main

jobs:
  merge-production-to-staging:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checkout repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      # Setup Git user
      - name: Set up Git
        run: |
          git config user.name "shicai-kooapps"
          git config user.email "146254365+shicai-kooapps@users.noreply.github.com"

      # Merge production into staging
      - name: Merge production into staging
        run: |
          # Fetch branch
          git fetch origin staging

          # Checkout staging branch
          git checkout staging
          git pull origin staging

          # Merge production branch
          git merge origin/main --no-ff -m "Automated merge from production to staging"

          # Push back to remote
          git push origin staging
          echo "{{github.actor}}"